### ISSUE TITLE
Always set height when ImgWidthHeight is set to true.

### ISSUE THREAD

**Issue by hakkva** [ErikHen/PictureRenderer#11]
To be able to remove CLS when using images with different ratios on the same profile, the height attribute should always be set.
for now the height attribute is only set when 
ImgWidthHeight  is true and you have an aspectratio>0 or FixedHeight is set.

**Comment by ErikHen** [comment]
Hi. Yeah, maybe it should be set by default for a "single-image". When showing multiple different images they might have different aspect ratios (and thus different heights). Then width and height can be set on the source element instead, at least Chrome and Safari supports it (https://web.dev/optimize-cls/#modern-best-practice).
It is however not possible to set the height without providing an aspect ratio. The height is calculated using the width and aspect ratio.
CLS can always be avoided using a container element and CSS.

Maybe I misunderstood you?

**Comment by hakkva** [comment]
The scenario is that in Optimizely in a block we want the user to be able to add any image, where we use your plugin to create different srcsets, However we do not want to limit the block to only one aspectratio. We want the user to be able to add an  image without worrying about aspect ratios, eg we do not know the sizes (could be 10x400 or 542x47)  and the height will be set based on that. Could a solution be that an overload is created where we pass in the original width and heights, taken from the imageblob,  that either is just set or calculated to new values for those profiles that do not use aspectratio or fixed width?

**Comment by ErikHen** [comment]
Ok, I understand. Would it solve your issue if you could set that the aspect ratio should be set to whatever the original image has, instead of specifying a fixed value?
That can be done, but... unfortunately Optimizely CMS does not store the image sizes (as far as I know). So you would need to store height and width on the image object yourself when a image is uploaded. Like this: https://world.optimizely.com/forum/developer-forum/Developer-to-developer/Thread-Container/2017/3/filling-image-width-and-height-automatically-in-imagedata/
Once that data is available it's an easy thing to extend PictureRenderer.Optimizely to use those values.

Would that approach work for you?

**Comment by hakkva** [comment]
We have access to that data so we can provide that to the the PicturerRenderer. So yes i think that approach will work.

**Comment by ErikHen** [comment]
Hi. I was just about to look into adding this feature, but I realize that you already can set the aspect ratio dynamically. If you know the height and width of the original image you can calculate the aspect ratio yourself, and create a new picture profile and send that as input parameter to the Renderer.
